name: 📺 Channel Request
description: Request to add a channel into the playlist
title: 'Add: '
labels: ['channel request']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form as much as you can so we could efficiently process your request

  - type: input
    attributes:
      label: Channel ID
      description: Unique channel ID from [iptv-org.github.io](https://iptv-org.github.io/).
      placeholder: 'BBCAmericaEast.us'
    validations:
      required: true

  - type: input
    attributes:
      label: Stream URL
      description: Link to the stream (if you have one)
      placeholder: 'https://example.com/playlist.m3u8'

  - type: textarea
    attributes:
      label: Notes
      description: 'Anything else we should know about this broadcast?'

  - type: checkboxes
    attributes:
      label: Please confirm the following
      options:
        - label: I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#request-a-channel)
          required: true
