name: 🛠 Broken Stream
description: Report a broken stream
title: 'Broken: '
labels: ['🛠 broken stream']

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the issue template as much as you can so we could efficiently process your request

  - type: input
    attributes:
      label: Stream Title
      description: Specify the exact title of the stream
      placeholder: 'BBC One (720p) [Not 24/7]'
    validations:
      required: true

  - type: input
    attributes:
      label: Playlist Link
      description: Provide a link to the playlist where you found this stream
      placeholder: 'https://iptv-org.github.io/iptv/index.category.m3u'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: What happened to the stream?
      options:
        - Not loading
        - Constantly interrupts/lagging
        - Stuck at a single frame
        - I see visual artifacts
        - Shows looped video
        - Shows the wrong channel
        - Displays a message asking to renew subscription
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes (optional)
      placeholder: 'Anything else we should know?'

  - type: checkboxes
    attributes:
      label: Please confirm the following
      options:
        - label: I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md#report-a-broken-stream)
          required: true
