name: 🗑 Remove stream link
description: Request to remove a stream link from the playlist
title: 'Remove: '
labels: ['streams:remove']

body:
  - type: input
    attributes:
      label: Stream URL
      description: Link to the stream from a playlist
      placeholder: 'https://lnc-kdfw-fox-aws.tubi.video/index.m3u8'
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Reason
      options:
        - Not loading
        - Constantly interrupts/lagging
        - Stuck at a single frame
        - Visual artifacts
        - Shows looped video
        - No sound
        - Displays a message asking to renew subscription
        - Duplicate
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Notes (optional)
      placeholder: 'Anything else we should know?'

  - type: checkboxes
    attributes:
      label: Contributing Guide
      description: 'Please read this guide before posting your request'
      options:
        - label: I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)
          required: true
