blank_issues_enabled: false
contact_links:
  - name: 📺 Channel request
    url: https://github.com/orgs/iptv-org/discussions/new/choose
    about: Looking for a link to the broadcast of the channel
  - name: 💡 Feature request
    url: https://github.com/orgs/iptv-org/discussions/new/choose
    about: For any ideas or feature requests
  - name: ❓ Ask a question
    url: https://github.com/orgs/iptv-org/discussions/new/choose
    about: Ask questions about this project
  - name: 🐞 Bug report
    url: https://github.com/orgs/iptv-org/discussions/new/choose
    about: Report an error in the repository
